### PR TITLE
Fixes to list mode, message width and anonymous styles

### PR DESCRIPTION
**Pull request by ghost**
Yo,

So you probably don't want to actually merge this, because my style of code is nothing like yours (I really dislike functions that are only invoked once), but I'm making the pull request anyway in case you want to take a look.

### CODE REVIEW

**Comment by TheZennou** [comment]
//Why yes, I copied all of these from my personal theme, how could you tell?
I did consider doing this as well, but decided emulating something close to the default theme might make it more anonymous. I did decide to add the anon picture though because it just felt more "Hey this is 4chan stuff ya know?"
As for the other changes, nothing jumps out as bad, just different to how I do it. I usually split everything into functions once everything gets big enough because it makes it easy to focus on one part of broken code and just test shit till it works (most of my coding is trial and error). 
I would like you to explain any other changes though, I see you're invoking your own styling, added debug mode, and just generally had cleaner implementation. Is there anything I'm missing?
The reason I ask, is because it doesn't properly return the image sizes to the users settings after an anonymize, nor is the grid mode as robust at handling odd message lengths. I'll take a look at fixing it this weekend if you're not up to it. Those improvements are quite sexy...! 
Here's your gridmode on a log from hell (and the anonymize styling not returning): 
Honeysgidmode
And here's mine, on the same log from hell:
mygridmode

**Comment by ghost** [comment]
>I did consider doing this as well, but decided emulating something close to the default theme might make it more anonymous. I did decide to add the anon picture though because it just felt more "Hey this is 4chan stuff ya know?"

Fair, fair. The green looks good too. I honestly did it because I was using Chrome devtools to see what CSS variables were even relevant so I could copy them over. And the names are a bit weird too.

>I usually split everything into functions once everything gets big enough because it makes it easy to focus on one part of broken code and just test shit till it works (most of my coding is trial and error).

Yeah, that's normal. I'm sick in the head so I just really like code I can read linearly, top to bottom.

>I would like you to explain any other changes though, I see you're invoking your own styling, added debug mode, and just generally had cleaner implementation. Is there anything I'm missing?

Homogenized list mode so it uses the same HTML as grid mode, just with slightly different CSS. Technically anonymous mode was reimplemented from scratch: I remove the user CSS entirely, banish the toggles' <link href element, then override all relevant CSS variables with the values I pulled from my ST. It should *very, very, very consistently* anonymize everything identifiable, but there might be differences between setups I'm not thinking of.

Also set anon mode to show token counts and hide times by default, to maximize anonymity. Then I hid away the buttons on the corner because they add nothing.

And max-height is now either the tallest message's height, or the square root of the grid area. This sort of (but not perfectly) makes logs more square-ish than the God-given numbers (and making them more square-ish is inherently better IMO because of 4chan/etc image limits).

>The reason I ask, is because it doesn't properly return the image sizes to the users settings after an anonymize, nor is the grid mode as robust at handling odd message lengths.

My bad, I don't understand the first issue and can't see the second because the log is blurry. Could you catbox them and email them to me at the usual email?

From here it looks to me like the log on the old version fucked up and cut the really long message midway.

**Comment by TheZennou** [comment]
> (and making them more square-ish is inherently better IMO because of 4chan/etc image limits).

This is a good idea, and the reason for grid mode in the first place, so this would be better.
>My bad, I don't understand the first issue.

My CSS for SillyTavern has larger images, when I use your anonymize styling, it will shrink them to match the parameters you've set up. The problem is that when the snapshot is finished, it's not returning the images to their larger sizes. All the other stuff like font, text color, etc is changing back properly, just not the images. 
> and can't see the second because the log is blurry.

I blurred the images on purpose, lmao. I'll make a log that doesn't have to be blurred and email you that before tomorrow, the old version does infact cut off the message if it runs into the vertical limit, it was possible to solve, but the background didn't extend to match it. 
The thing I was bringing up is how your version reacts, with the large gaps between messages, vertically.

**Comment by ghost** [comment]
>My CSS for SillyTavern has larger images, when I use your anonymize styling, it will shrink them to match the parameters you've set up. The problem is that when the snapshot is finished, it's not returning the images to their larger sizes. All the other stuff like font, text color, etc is changing back properly, just not the images.

Interesting. Could you tell me how are you changing the image sizes?

```css
.mes {
  --avatar-base-height: 100px;
  --avatar-base-width: 100px;
  --avatar-base-border-radius-round: 0px;
}
```

works fine for me and switches back normally. Might be a CSS rule resolution issue.

>The thing I was bringing up is how your version reacts, with the large gaps between messages, vertically.

I think that's just the flexbox tbqh. The gaps are smaller on the other screenshot you sent because it cuts the largest message and has less space to fill.

**Comment by cloak1505** [comment]
In line 43 of commit 4edff85b you have `shieldWidth`, did you mean `sheldWidth`?

**Pull request merged**
